name: deploy

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy.yml'
      - 'apps/moing/**'
      - 'packages/**'
      - 'package-lock.json'
      - 'package.json'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/deploy.yml'
      - 'apps/moing/**'
      - 'packages/**'
      - 'package-lock.json'
      - 'package.json'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up checkout
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm # https://github.com/actions/setup-node#caching-global-packages-data

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:m
        env:
          BACKEND_PORT: ${{ vars.BACKEND_PORT }}
          BACKEND_IP: ${{ vars.BACKEND_IP }}

      - name: Upload static files as artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./apps/moing/build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    if: github.ref == 'refs/heads/main'

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
