name: deploy

on:
  push:
    branches: [main]
    paths:
      - 'apps/moing/**'
      - 'packages/**'
      - 'package-lock.json'

  pull_request:
    branches: [main]
    paths:
      - 'apps/moing/**'
      - 'packages/**'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up checkout
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm # https://github.com/actions/setup-node#caching-global-packages-data

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        run: |
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
          echo "BACKEND_IP=${{ secrets.BACKEND_IP }}" >> .env

      - name: Build
        run: npm run build:m

      - name: Deployment
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/moing/build
